# Generated by Django 3.2.20 on 2023-07-23 16:49

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
