# Generated by Django 3.2.20 on 2023-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
