# Generated by Django 3.2.20 on 2023-07-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'Faqs'},
        ),
    ]
